{
 "title": "Sample Amazon Timestream Dashboard",
 "tags": [
  "Amazon Timeseries",
  "sample"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "device_id",
    "label": "Device",
    "query": "SELECT distinct DeviceID FROM \"TimestreamDB\".\"SampleMetricsTable\""
   },
   {
    "name": "measure",
    "label": "Measure",
    "query": "SELECT distinct measure_name FROM \"TimestreamDB\".\"SampleMetricsTable\""
   }
  ]
 },
 "panels": [
  {
   "title": "Single device measure",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measure": "voltage_L1",
     "rawQuery": "SELECT DeviceID, BIN(time, $__interval_ms) AS time_bin, ROUND(AVG(measure_value::double), 2) AS avg_value, ROUND(APPROX_PERCENTILE(measure_value::double, 0.9), 2) AS p90_value, ROUND(APPROX_PERCENTILE(measure_value::double, 0.95), 2) AS p95_value, ROUND(APPROX_PERCENTILE(measure_value::double, 0.99), 2) AS p99_value FROM $__database.$__table WHERE $__timeFilter AND measure_name = '${measure}' AND DeviceID = '${device_id}' GROUP BY DeviceID, BIN(time, $__interval_ms) ORDER BY p99_value DESC"
    }
   ]
  },
  {
   "title": "Count measurements reads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawQuery": "SELECT CASE WHEN measure_name = 'voltage_measure' THEN count_value ELSE NULL END AS voltage,\n    CASE WHEN measure_name = 'watt_measure' THEN count_value ELSE NULL END AS watt,\n    CASE WHEN measure_name = 'temperature_measure' THEN count_value ELSE NULL END AS temperature,\n    CASE WHEN measure_name = 'humidity_measure' THEN count_value ELSE NULL END AS humidity\nFROM (\n    SELECT measure_name, Count(*) AS count_value\n    FROM  $__database.$__table\n    Group BY measure_name\n)"
    }
   ]
  },
  {
   "title": "Measure",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawQuery": "SELECT measure_value::double as ${measure} FROM $__database.$__table where measure_name = '${measure}' AND $__timeFilter"
    }
   ]
  },
  {
   "title": "Measure value spectrum for all devices",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawQuery": "select * from $__database.$__table\nWHERE $__timeFilter\nAND measure_name = '${measure}'"
    }
   ]
  },
  {
   "title": "Measure of a single device",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawQuery": "SELECT time, measure_value::double as ${measure} FROM $__database.$__table WHERE measure_name = '${measure}' AND DeviceID = '${device_id}' AND $__timeFilter order by time DESC"
    }
   ]
  },
  {
   "title": "Measure all devices",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "rawQuery": "SELECT DeviceID, CREATE_TIME_SERIES(time, measure_value::double) FROM $__database.$__table WHERE $__timeFilter AND measure_name = '${measure}' group by DeviceID"
    }
   ]
  }
 ]
}